---
driver:
  name: terraform
  variable_files:
    - test.auto.tfvars

provisioner:
  name: terraform

platforms:
  - name: github

verifier:
  name: terraform
  systems:
    - name: default
      backend: local

suites:
  - name: default
